name: bayesian_aggregation
channels:
  - defaults
dependencies:
  - pip=20.2.3
  - python=3.8
  - pip:
    - matplotlib==3.3.2
    - numpy==1.19.2
    - pyyaml==5.3.1
    - scipy==1.5.2
    - tensorboard==2.3.0
    - torch==1.4.0
    - torchvision==0.5.0
    - tqdm==4.50.0
